### PR TITLE
chore(deps): bump https://github.com/ajureeruja/conference-site from 0.0.15 to 0.0.19

### PR DESCRIPTION
**Pull request by ajureeruja**
Update [ajureeruja/conference-site](https://github.com/ajureeruja/conference-site) from 0.0.15 to [0.0.19](https://github.com/ajureeruja/conference-site/releases/tag/v0.0.19)

Command run was `jx step create pr chart --name conference-site --version 0.0.19 --repo https://github.com/salaboy/conference-helm-chart.git`

### CODE REVIEW

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **salaboy**

If they are not already assigned, you can assign the PR to them by writing `/assign @salaboy` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=salaboy%2Fconference-helm-chart).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/salaboy/conference-helm-chart/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by salaboy** [comment]
Hi @ajureeruja. Thanks for your PR.

I'm waiting for a [salaboy](https://github.com/orgs/salaboy/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/salaboy/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=salaboy%2Fconference-helm-chart).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by salaboy** [comment]
@ajureeruja I can see that you have been using my examples! that is great! Let me know if I can help with something or if you have questions.. Thanks for closing the PR as well :) 
Cheers

**Comment by salaboy** [comment]
@ajureeruja notice that the latest examples are prefixed with `demo-` like `demo-conference-site`

**Comment by ajureeruja** [comment]
Yea, I forgot to edit the jenkins-x.yml file, my apologies.  I'm sure I will have plenty of questions. How would you prefer to be contacted for questions?  Do you have a link to a demo utilizing the new demo- repos?  Thanks!

**Comment by ajureeruja** [comment]
and thanks for all your work in providing all these demos!

**Comment by salaboy** [comment]
Yeah here https://github.com/salaboy?utf8=✓&tab=repositories&q=demo-conference&type=&language=

Feel free to create issues in those repos if you have questions or Twitter

**Pull request closed without merging**
